export { default as Home } from './Home/Home'
export { default as Navi } from './Navi/Navi'
export { default as Gallary } from './Gallary/Gallary'
export { default as Aboutus } from './Aboutus/Aboutus'
export { default as Services } from './Services/Services'